# Generated by Django 4.2 on 2023-04-23 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_imageabout_alt_alter_social_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
