# Generated by Django 4.2 on 2023-04-23 22:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_about_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='max_text',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
